"""initial schema

Revision ID: 2fd40a026421
Revises: 
Create Date: 2026-05-07 14:59:14.896080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd40a026421'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email_encrypted', sa.Text(), nullable=False),
    sa.Column('email_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('document_encrypted', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=8), nullable=False),
    sa.Column('document_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('extra_metadata', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_document_fingerprint'), 'customers', ['document_fingerprint'], unique=False)
    op.create_index(op.f('ix_customers_email_fingerprint'), 'customers', ['email_fingerprint'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=True),
    sa.Column('secret_hash', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('dunning_step', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_next_billing_date'), 'subscriptions', ['next_billing_date'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('endpoint_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_response_code', sa.Integer(), nullable=True),
    sa.Column('last_response_body', sa.Text(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_deliveries_created', 'webhook_deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_endpoint_id'), 'webhook_deliveries', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_event_id'), 'webhook_deliveries', ['event_id'], unique=False)
    op.create_table('charges',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=True),
    sa.Column('subscription_id', sa.String(length=40), nullable=True),
    sa.Column('txid', sa.String(length=35), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('pix_payload', sa.Text(), nullable=False),
    sa.Column('qr_code_base64', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_charges_idem'),
    sa.UniqueConstraint('txid', name='uq_charges_txid')
    )
    op.create_index(op.f('ix_charges_customer_id'), 'charges', ['customer_id'], unique=False)
    op.create_index('ix_charges_status_due', 'charges', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_charges_subscription_id'), 'charges', ['subscription_id'], unique=False)
    op.create_table('dunning_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.String(length=40), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('charge_id', sa.String(length=40), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dunning_log_subscription_id'), 'dunning_log', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dunning_log_subscription_id'), table_name='dunning_log')
    op.drop_table('dunning_log')
    op.drop_index(op.f('ix_charges_subscription_id'), table_name='charges')
    op.drop_index('ix_charges_status_due', table_name='charges')
    op.drop_index(op.f('ix_charges_customer_id'), table_name='charges')
    op.drop_table('charges')
    op.drop_index(op.f('ix_webhook_deliveries_event_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_endpoint_id'), table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_created', table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_subscriptions_next_billing_date'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('webhook_endpoints')
    op.drop_table('plans')
    op.drop_index(op.f('ix_customers_email_fingerprint'), table_name='customers')
    op.drop_index(op.f('ix_customers_document_fingerprint'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
